version: '3.8'

services:
  vitepress:
    image: node:18
    container_name: vitepress-container
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:5173" # Expose port 5173 (default VitePress dev server port) to port 3000 on the host
    command: sh -c "npm install && npm run docker:docs:dev"